version: "3"
services:
  mongo:
    image: "mongo"
    environment:
      - MONGO_INITDB_DATABASE=bora-upload
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - "27017:27017"
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.11-1.1.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "issue-upload:1:1,upload-response:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
